version: 2

models:
  - name: stg_bigbasket_prices
    columns:
      - name: product_name
        tests: [not_null]
      - name: price_per_kg
        tests: [not_null]
      - name: scraped_date
        tests: [not_null]

  - name: stg_mandi_prices
    columns:
      - name: commodity
        tests: [not_null]
      - name: modal_price_per_kg
        tests: [not_null]
      - name: arrival_date
        tests: [not_null]
